services:
  je-donne-je-prete:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}

    env_file:
      - .env

    image: je-donne-je-prete:latest
    container_name: je-donne-je-prete

    ports:
      - 0.0.0.0:${PORT}:${PORT}

    environment:
      - HOST=0.0.0.0
      - PORT=${PORT}

    restart: always



  db:
    image: docker.io/library/mysql:8.0
    container_name: db

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    restart: always
